### PR TITLE
Add configurable chance

### PR DESCRIPTION
**Pull request by datatags**
Thought this would be a fun feature.  That way you can never be sure if the creeper is going to blow up your house or not. 😄 The chance is set to 100, always confetti creepers, by default.

### CODE REVIEW

**Comment by askrealcookie** [comment]
Oh, nice addition, sorry for late response, I am busy with school right now. I will look into it and merge it asap. Thanks for making pr!

**Comment by datatags** [comment]
> 
> 
> Oh, nice addition, sorry for late response, I am busy with school right now. I will look into it and merge it asap. Thanks for making pr!

Hello, have you had a chance to look into this yet?  I'd love to use this feature in a release build!

**Comment by askrealcookie** [comment]
Hey, sorry for that long waiting time, I really had a lot of exams, it's now somehow stable and I can work on it. Tomorrow(EU time) I'll try to do something with that. Sorry again!

**Comment by datatags** [comment]
> 
> 
> Hey, sorry for that long waiting time, I really had a lot of exams, it's now somehow stable and I can work on it. Tomorrow(EU time) I'll try to do something with that. Sorry again!

Ok cool, thanks! :)

**Comment by askrealcookie** [comment]
Okay, you waited waaaay too much time for this change to merge with main branch. I am sorry for that, but I was really busy recently and also I am learning Github pretty much from scratch. Your code looks and works good, great job and thanks for contributing! I hope to make updates more frequently..

**Comment by datatags** [comment]
No problem, happy to help!  Good luck!

**Pull request merged**
